name: CI
on: push
jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run test
        shell: bash
        run: |
          ls
          ./test-flag-alt-text.sh
