name: Test Accessibility-alt-text-bot
on: 
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  accessibility_alt_text_bot:
    name: Check alt text is set on issue or pull requests
    runs-on: ubuntu-latest
    if: ${{ github.event.issue || github.event.pull_request && github.event.comment.user.login != 'accessibility-bot' }}
    steps:
      - name: Get private action 'github/accessibility-alt-text-bot'
        uses: actions/checkout@v2
        with:
          repository: github/accessibility-alt-text-bot
          token: ${{ secrets.GH_TOKEN }}
          path: ./.github/actions/github/accessibility-alt-text-bot
      - name: Check alt text
        uses: ./.github/actions/github/accessibility-alt-text-bot
